//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 05:29:15 PM CEST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImportNalogZaPlacanjeRequest }
     * 
     */
    public ImportNalogZaPlacanjeRequest createImportNalogZaPlacanjeRequest() {
        return new ImportNalogZaPlacanjeRequest();
    }

    /**
     * Create an instance of {@link GetM103Response }
     * 
     */
    public GetM103Response createGetM103Response() {
        return new GetM103Response();
    }

    /**
     * Create an instance of {@link GetM102Response }
     * 
     */
    public GetM102Response createGetM102Response() {
        return new GetM102Response();
    }

    /**
     * Create an instance of {@link ImportNalogZaPlacanjeResponse }
     * 
     */
    public ImportNalogZaPlacanjeResponse createImportNalogZaPlacanjeResponse() {
        return new ImportNalogZaPlacanjeResponse();
    }

    /**
     * Create an instance of {@link GetM103Request }
     * 
     */
    public GetM103Request createGetM103Request() {
        return new GetM103Request();
    }

    /**
     * Create an instance of {@link GetM102Request }
     * 
     */
    public GetM102Request createGetM102Request() {
        return new GetM102Request();
    }

}
